<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use app\models\ContactQuery;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "contacts".
 *
 * @property integer $id
 * @property string $phone
 * @property string $working_days
 * @property string $working_times
 * @property string $info
 * @property string $map
 * @property string $address
 * @property string $meta_keywords
 * @property string $meta_description
 */
abstract class Contact extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contacts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['info', 'map'], 'string'],
            [['phone'], 'string', 'max' => 55],
            [['working_days', 'working_times', 'address', 'meta_keywords', 'meta_description'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'phone' => 'Phone',
            'working_days' => 'Working Days',
            'working_times' => 'Working Times',
            'info' => 'Info',
            'map' => 'Map',
            'address' => 'Address',
            'meta_keywords' => 'Meta Keywords',
            'meta_description' => 'Meta Description',
        ]);
    }

    /**
     * @inheritdoc
     * @return ContactQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ContactQuery(static::class);
    }
}
