<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\DeliveryTypeQuery;

/**
 * This is the base-model class for table "delivery_types".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $price
 *
 * @property \app\models\Cart[] $carts
 */
abstract class DeliveryType extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'delivery_types';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description'], 'string'],
            [['price'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'price' => 'Price',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarts()
    {
        return $this->hasMany(\app\models\Cart::class, ['delivery_types_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return DeliveryTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DeliveryTypeQuery(static::class);
    }
}
