<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\NumberQuery;

/**
 * This is the base-model class for table "number".
 *
 * @property integer $id
 * @property integer $a
 * @property integer $b
 */
abstract class Number extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'number';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['a', 'b'], 'integer'],
            [['a', 'b'], 'required' ]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'a' => 'A',
            'b' => 'B',
        ]);
    }

    /**
     * @inheritdoc
     * @return NumberQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new NumberQuery(static::class);
    }
}
