<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\PaycomTransactionQuery;

/**
 * This is the base-model class for table "paycom_transactions".
 *
 * @property integer $id
 * @property string $paycom_transaction_id
 * @property string $paycom_time
 * @property string $paycom_time_datetime
 * @property string $create_time
 * @property string $perform_time
 * @property string $cancel_time
 * @property integer $amount
 * @property integer $state
 * @property integer $reason
 * @property integer $order_id
 *
 * @property \app\models\Order $order
 */
abstract class PaycomTransaction extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'paycom_transactions';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['paycom_time_datetime', 'create_time', 'perform_time', 'cancel_time'], 'safe'],
            [['amount', 'state', 'reason', 'order_id'], 'integer'],
            [['paycom_transaction_id'], 'string', 'max' => 25],
            [['paycom_time'], 'string', 'max' => 13],
            [['order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Order::class, 'targetAttribute' => ['order_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'paycom_transaction_id' => 'Paycom Transaction ID',
            'paycom_time' => 'Paycom Time',
            'paycom_time_datetime' => 'Paycom Time Datetime',
            'create_time' => 'Create Time',
            'perform_time' => 'Perform Time',
            'cancel_time' => 'Cancel Time',
            'amount' => 'Amount',
            'state' => 'State',
            'reason' => 'Reason',
            'order_id' => 'Order ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(\app\models\Order::class, ['id' => 'order_id']);
    }

    /**
     * @inheritdoc
     * @return PaycomTransactionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PaycomTransactionQuery(static::class);
    }
}
