<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ProductQuery;
use yii\db\Expression;

/**
 * This is the base-model class for table "products".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property double $price
 * @property integer $category_product_id
 * @property string $slug
 * @property string $details
 * @property integer $quantity
 * @property integer $is_best_sell
 * @property integer $product_status
 * @property integer $user_id
 * @property string $deleted_at
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\CategoryProduct $categoryProduct
 * @property \app\models\OrderItem[] $orderItems
 */
abstract class Product extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => new Expression('NOW()'),
            ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description', 'details'], 'string'],
            [['price'], 'number'],
            [['category_product_id', 'quantity', 'is_best_sell', 'product_status', 'user_id'], 'integer'],
            [['deleted_at'], 'safe'],
            [['name', 'slug'], 'string', 'max' => 255],
            [['category_product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CategoryProduct::class, 'targetAttribute' => ['category_product_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'price' => 'Price',
            'category_product_id' => 'Category Product ID',
            'slug' => 'Slug',
            'details' => 'Details',
            'quantity' => 'Quantity',
            'is_best_sell' => 'Is Best Sell',
            'product_status' => 'Product Status',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryProduct()
    {
        return $this->hasOne(\app\models\CategoryProduct::class, ['id' => 'category_product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItems()
    {
        return $this->hasMany(\app\models\OrderItem::class, ['product_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(static::class);
    }
}
