<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\query\ProductQuery;
use yii2tech\ar\softdelete\SoftDeleteBehavior;
use yii2tech\ar\position\PositionBehavior;

/**
 * This is the base-model class for table "products".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property double $price
 * @property integer $category_product_id
 * @property string $slug
 * @property string $detail
 * @property integer $availabel_stock
 * @property integer $is_best_sell
 * @property integer $status
 * @property string $deleted_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Cart[] $carts
 * @property \app\models\CategoryProduct $categoryProduct
 * @property \app\models\Comment[] $comments
 * @property \app\models\User $createdBy
 * @property \app\models\OrderItem[] $orderItems
 * @property \app\models\ProductImage[] $productImages
 * @property \app\models\User $updatedBy
 */
abstract class Product extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];
        $behaviors['softDelete'] = [
            'class' => SoftDeleteBehavior::class,
            'softDeleteAttributeValues' => [
                'deleted_at' => date('Y-m-d H:i:s'),
            ],
            'replaceRegularDelete' => true
        ];
        $behaviors['position'] = [
            'class' => PositionBehavior::class,
            'positionAttribute' => 'position',
        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description', 'detail'], 'string'],
            [['price'], 'number'],
            [['category_product_id', 'availabel_stock', 'is_best_sell', 'status'], 'integer'],
            [['deleted_at'], 'safe'],
            [['name', 'slug'], 'string', 'max' => 255],
            [['category_product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CategoryProduct::class, 'targetAttribute' => ['category_product_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['updated_by' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'price' => 'Price',
            'category_product_id' => 'Category Product ID',
            'slug' => 'Slug',
            'detail' => 'Detail',
            'availabel_stock' => 'Availabel Stock',
            'is_best_sell' => 'Is Best Sell',
            'status' => 'Status',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarts()
    {
        return $this->hasMany(\app\models\Cart::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryProduct()
    {
        return $this->hasOne(\app\models\CategoryProduct::class, ['id' => 'category_product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(\app\models\Comment::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItems()
    {
        return $this->hasMany(\app\models\OrderItem::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductImages()
    {
        return $this->hasMany(\app\models\ProductImage::class, ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'updated_by']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(static::class);
    }
}
