<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\SmQuery;

/**
 * This is the base-model class for table "sms".
 *
 * @property integer $id
 * @property string $phone
 * @property integer $sms
 * @property integer $try_count
 * @property integer $send_at
 */
abstract class Sm extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sms';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['sms', 'try_count', 'send_at'], 'integer'],
            [['phone'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'phone' => 'Phone',
            'sms' => 'Sms',
            'try_count' => 'Try Count',
            'send_at' => 'Send At',
        ]);
    }

    /**
     * @inheritdoc
     * @return SmQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SmQuery(static::class);
    }
}
