<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\UserDeliveryAddressQuery;

/**
 * This is the base-model class for table "user_delivery_address".
 *
 * @property integer $id
 * @property integer $place_id
 * @property integer $user_id
 * @property string $address
 * @property double $lat
 * @property double $lng
 * @property string $phone
 */
abstract class UserDeliveryAddress extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_delivery_address';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['place_id', 'user_id'], 'integer'],
            [['lat', 'lng'], 'number'],
            [['address'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 55]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'place_id' => 'Place ID',
            'user_id' => 'User ID',
            'address' => 'Address',
            'lat' => 'Lat',
            'lng' => 'Lng',
            'phone' => 'Phone',
        ]);
    }

    /**
     * @inheritdoc
     * @return UserDeliveryAddressQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserDeliveryAddressQuery(static::class);
    }
}
