<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use app\models\UserDeliveryAddressQuery;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "user_delivery_address".
 *
 * @property integer $id
 * @property integer $place_id
 * @property integer $user_id
 * @property string $address
 * @property double $lat
 * @property double $lng
 * @property string $phone
 *
 * @property \app\models\Place $place
 * @property \app\models\User $user
 */
abstract class UserDeliveryAddress extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_delivery_address';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['place_id', 'user_id'], 'integer'],
            [['lat', 'lng'], 'number'],
            [['address'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 55],
            [['place_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Place::class, 'targetAttribute' => ['place_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['user_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'place_id' => 'Place ID',
            'user_id' => 'User ID',
            'address' => 'Address',
            'lat' => 'Lat',
            'lng' => 'Lng',
            'phone' => 'Phone',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlace()
    {
        return $this->hasOne(\app\models\Place::class, ['id' => 'place_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'user_id']);
    }

    /**
     * @inheritdoc
     * @return UserDeliveryAddressQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserDeliveryAddressQuery(static::class);
    }
}
