<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\VideoGalleryQuery;

/**
 * This is the base-model class for table "video_gallery".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $url
 * @property string $meta_keywords
 * @property string $meta_description
 */
abstract class VideoGallery extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name', 'description', 'url', 'meta_keywords', 'meta_description'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'url' => 'Url',
            'meta_keywords' => 'Meta Keywords',
            'meta_description' => 'Meta Description',
        ]);
    }

    /**
     * @inheritdoc
     * @return VideoGalleryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new VideoGalleryQuery(static::class);
    }
}
